[2024-02-25 06:21:57,173] 160 numexpr.utils - INFO -NumExpr defaulting to 4 threads.
[2024-02-25 06:22:13,215] 241 django.request - ERROR -Internal Server Error: /tab
Traceback (most recent call last):
  File "C:\Users\DELL\Anaconda3\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\DELL\Anaconda3\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\DELL\PycharmProjects\django\myproject\trade\views.py", line 469, in tab
    collection_data = list(db[collection_name].find())
  File "C:\Users\DELL\Anaconda3\lib\site-packages\pymongo\database.py", line 237, in __getitem__
    return Collection(self, name)
  File "C:\Users\DELL\Anaconda3\lib\site-packages\pymongo\collection.py", line 208, in __init__
    raise InvalidName("collection names cannot be empty")
pymongo.errors.InvalidName: collection names cannot be empty
[2024-02-25 06:22:24,304] 241 django.request - ERROR -Internal Server Error: /tab
Traceback (most recent call last):
  File "C:\Users\DELL\Anaconda3\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\DELL\Anaconda3\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\DELL\PycharmProjects\django\myproject\trade\views.py", line 469, in tab
    collection_data = list(db[collection_name].find())
  File "C:\Users\DELL\Anaconda3\lib\site-packages\pymongo\database.py", line 237, in __getitem__
    return Collection(self, name)
  File "C:\Users\DELL\Anaconda3\lib\site-packages\pymongo\collection.py", line 208, in __init__
    raise InvalidName("collection names cannot be empty")
pymongo.errors.InvalidName: collection names cannot be empty
[2024-02-25 06:23:30,216] 266 django.utils.autoreload - INFO -C:\Users\DELL\PycharmProjects\django\myproject\trade\views.py changed, reloading.
